---
- name: conditional demo playbook
  hosts: all
  tasks:
    - name: Install httpd on redhat or centos which are the part web server group
      yum: name=httpd state=present
      when: (ansible_facts['os_family'] == "RedHat" or ansible_facts['distribution'] == 'CentOS') and ("webservers" in group_names)

    - name: install the nginx software
      yum: name=nginx state=present
      when: (ansible_facts['os_family'] == "RedHat" and inventory_hostname.startswith('node')) and ("webservers" in group_names)
