---
- name: Demo for free strategy
  hosts: all
  strategy: free
  tasks:
    - name: this is task-1 simulate slow task
      command: sleep 15

    - name: this is task-2 simulate the faster task
      command: sleep 5

    - name: this is task-3 will just printing
      debug:
        msg: "hurray I am working on free strategy" 

