---
- name: Only install the package if both the conditions are true
  hosts: all
  tasks:
    - name: installation of the tree
      package: name=tree state=present
      register: yum_output
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version'] | int  >= 8
