---
- name: Uninstall the web server on remote machine #Play Name
  hosts: all
  tasks:
    - name: uninstall web server
      yum: name=httpd state=absent

        #- name: Start the webserver
        #service: name=httpd state=started
- name: Install tree package on the remote machine  #Play Name
  hosts: all
  tags: db
  tasks:
    - name: Install tree package
      yum: name=tree state=absent
